#[[files]]
#type="revealjs"
#infile="KiCadWorkshop_en.md"
#outfile="slides.html"
#variables=[
#    "theme=moon"
#]

#[[files]]
#type="odt"
#infile="docu.md"
#outfile="docu.odt"
#converter="pandoc"

[[files]]
title="Make> your own shitty addon"
subtitle="Welcome to \\#badgelife"
author="Tillo"
date="\\today"
type="pdf" 
infile="docu.md"
outfile="docu.pdf"
pdfengine="xelatex" # pdflatex, lualatex, xelatex, latexmk, tectonic, wkhtmltopdf, weasyprint, prince, context, and pdfroff
converter="pandoc"
header="docu_header.tex"
toc=true
numbered=true
verbose=true
codestyle="pygments" # pygments, kate, monochrome, espesso, haddock, zenburn, tango
variables=[
    "documentclass=scrartcl",
    "fontsize=10pt",
    "papersize=a4",
    "lang=en",
    "urlcolor=red",
]

[[files]]
type="beamer"
converter="pandoc"
infile="KiCadWorkshop_en.md"
outfile="beamer.pdf"
header="beamer_header.tex"
pdfengine="xelatex" # pdflatex, lualatex, xelatex, latexmk, tectonic, wkhtmltopdf, weasyprint, prince, context, and pdfroff